name: Generate Javadocs

on:
  push:
    branches:
      - main  # Adjust to your primary branch (e.g., main, master)

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Replace with your Java version (e.g., 11, 17)
          distribution: 'temurin'

      - name: Generate Javadocs
        run: |
          javadoc -d ./src/grpro_projekt_docs -sourcepath ./src -subpackages . || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/grpro_projekt_docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}