name: Generate Javadocs

on:
  push:
    branches:
      - main  # Adjust to your primary branch (e.g., main, master)

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Replace with your Java version (e.g., 11, 17)
          distribution: 'temurin'

      - name: Create docs directory
        run: |
          mkdir -p ./docs

      # Step 3: Generate Javadocs (allow failure)
      - name: Generate Javadocs
        run: |
          javadoc -d ./docs -sourcepath ./src $(find ./code/src -name "*.java" -not -path "./src/itumulator/*") || true

      # Step 4: Publish Javadocs to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
