name: Generate Javadocs

on:
  push:
    branches:
      - master
      - main # Adjust to your primary branch (e.g., main, master)

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '23'  # Replace with your Java version (e.g., 11, 17)
          distribution: 'temurin'

      - name: autism
        run: |
          mkdir docs
          echo "asdadjhasjd" > children.txt

      # Step 4: Generate Javadocs
      - name: Generate Javadocs
        run: |
          javadoc -d ./docs -sourcepath ./src $(find ./src -name "*.java" -not -path "./src/itumulator/*") || true
      - name: Verify Javadoc files
        run: |
          ls -l ./docs | grep '.html$' || { echo "No HTML files found in docs directory"; exit 1; }
              
      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
