name: Deploy Javadoc

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches: [ master ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Generate Javadoc
        run: |
          mkdir -p javadoc
          javadoc -d javadoc -sourcepath src/ -subpackages .
          
      - name: Create .nojekyll to Disable Jekyll
        run: echo "" > javadoc/.nojekyll
        
      - name: Deploy Javadoc to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: javadoc
          folder: javadoc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify working directory
        run: ls -la

      - name: Debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of javadoc directory:"
          ls -la javadoc
